name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7"]
        platform: [octave]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Octave (Linux)
        if: matrix.platform == 'octave'
        uses: MATPOWER/action-install-octave-linux@v1
      - name: Install dependencies
        run: |
          python -m pip install -U pip install wheel setuptools cffi
          pip install -r requirements-dev.txt
          pip install -e "."
      - name: Install pytest dependencies
        run: |
          pip install pytest pytest-ordering pytest-cov pytest-runner
      - name: Generate coverage report
        run: |
          pytest -vvv -n auto --cov=matpowercaseframes --cov-report=xml:unit.coverage.xml

      # - name: Upload unit test coverage to Codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ./unit.coverage.xml
      #     flags: unit
      #     env_vars: PYTHON
      #     name: codecov-unit
      #     fail_ci_if_error: false
