name: publish

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        platform: [octave]
        os: [ubuntu-latest]

    runs-on: ${{matrix.os}}

    steps:
      - name: Clone this repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'requirements-dev.txt'

      - name: Install Octave (Linux)
        if: matrix.platform == 'octave'
        uses: MATPOWER/action-install-octave-linux@v1

      - name: Install requirements
        run: |
          pip install -r requirements-dev.txt

      - name: Install package
        run: |
          pip install -e .

      - name: Generate coverage report
        run: |
          pytest -vvv -n auto --cov=matpowercaseframes --cov-report=xml:unit.coverage.xml

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Clone this repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: 'requirements-dev.txt'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
